// import { ReactElement } from 'react'

import Head from 'next/head'

import { ReactQuery } from '@components'
import styles from '@styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ReactQuery />
      </main>
    </div>
  )
}

// Home.getLayout = function getLayout(page: ReactElement) {
//   return <Layout>{page}</Layout>
// }
